### ISSUE TITLE
Firma

### ISSUE THREAD

**Issue by BinniZenobioCordovaLeandro** [BinniZenobioCordovaLeandro/ose.xml.validator#2]

**Comment by binnicordova** [comment]
This was closed with:
Merge pull request #7 from BinniZenobioCordovaLeandro/bcordova
conditions loaded 7% - Firma
![image](https://user-images.githubusercontent.com/42467277/64873009-d9e39380-d60d-11e9-8c1e-6b18366adfe0.png)
